version: "3.8"

services:
  dind:
    container_name: dind
    image: docker:dind
    privileged: true
    command: --storage-driver=overlay2
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./jenkins-docker-certs:/certs/client
    ports:
      - 2376:2376
      
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:jdk11
    networks:
      jenkins:
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client 
      - DOCKER_TLS_VERIFY=1
    ports:
      - 8080:8080
      - 50000:50000 
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./jenkins-docker-certs:/certs/client

networks:
  jenkins: